KerasJson: example-keras-model-files/KERAS_3layer_batch_norm.json
KerasH5:   example-keras-model-files/KERAS_3layer_batch_norm_weights.h5
InputData: example-keras-model-files/KERAS_3layer_input_features.dat
OutputPredictions: example-keras-model-files/KERAS_3layer_batch_norm_predictions.dat
OutputDir: my-hls-test-3layer-batchnorm
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i

ReuseFactor: 1
DefaultPrecision: ap_fixed<16,6> 
