KerasJson: example-keras-model-files/KERAS_3layer_ternary.json
KerasH5:   example-keras-model-files/KERAS_3layer_ternary_weights.h5
InputData: example-keras-model-files/KERAS_3layer_binary_input_features.dat
OutputPredictions: example-keras-model-files/KERAS_3layer_ternary_predictions.dat
OutputDir: my-hls-test-3layer-ternary
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i

ReuseFactor: 1
DefaultPrecision: ap_fixed<16,6> 
